### ISSUE TITLE
Possible problem with JSON Feed

### ISSUE THREAD

**Issue by PezHead** [NSHipster/nshipster.com#38]
Hello, I've tried loading the JSON Feed (https://nshipster.com/feed.json) into a couple of different readers and they all seem to be having a problem parsing the JSON. Looking at the response, I think the problem might be in the `content_html` properties. It looks like there is a leading line-break in each of the values.

**Comment by jbrayton** [comment]
I noticed this as well. I believe the problem is that the content_html attributes contain line break characters that are not escaped. You can see the issue with this line:

`curl https://nshipster.com/feed.json | python -m json.tool`

It complains about the first line break character inside the first content_html attribute.

**Comment by mattt** [comment]
After more trial and error than I'd like to admit, I [managed to get JSONFeed validating successfully](https://validator.jsonfeed.org/?url=https%3A%2F%2Fnshipster.com%2Ffeed.json). Thanks for reporting this, @PezHead and @jbrayton. Please let me know if you run into any other issues with this.

**Comment by PezHead** [comment]
Thanks so much for fixing this @mattt. My feed reader app is much happier for it :]
